- name: Create directory of wordpress volume
  ansible.builtin.file:
    path: /root/data/wp
    state: directory

- name: Start wordpress 
  ansible.builtin.shell:
    cmd: docker compose up -d --build wordpress
    chdir: /root/app/srcs

