- name: Setup Project 
  hosts: myhost
  remote_user: root
  roles:
    - setup_project

- name: Run mariadb 
  hosts: myhost
  remote_user: root
  roles:
    - start_mariadb 

- name: Run wordpress 
  hosts: myhost
  remote_user: root
  roles:
    - start_wordpress

- name: Run nginx 
  hosts: myhost
  remote_user: root
  roles:
    - start_nginx 

