- name: Create directory of wordpress volume
  ansible.builtin.file:
    path: /root/data/wp
    state: directory

- name: Start nginx 
  ansible.builtin.shell:  
    cmd: docker compose up -d --build nginx
    chdir: /root/app/srcs
     
